from typing import Protocol


class CrawlerProvider(Protocol):
    def start(self, url: str, *, limit: int, metadata: dict) -> dict: ...

    def status(self, crawl_id: str) -> dict: ...

    def cancel(self, crawl_id: str) -> None: ...

    def verify_webhook(self, body: bytes, signature: str | None) -> bool: ...
