"""add wordpress audits

Revision ID: 0002_wordpress_audits
Revises: 0001_identity_projects
Create Date: 2026-06-13 02:09:41.346916
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_wordpress_audits"
down_revision: str | None = "0001_identity_projects"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wordpress_connections",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("site_url", sa.String(length=2048), nullable=False),
        sa.Column("encrypted_secret", sa.Text(), nullable=False),
        sa.Column("plugin_version", sa.String(length=32), nullable=True),
        sa.Column("seo_plugin", sa.String(length=32), nullable=True),
        sa.Column(
            "health_state",
            sa.String(length=24),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wordpress_connections_project_id"),
        "wordpress_connections",
        ["project_id"],
        unique=True,
    )
    op.create_table(
        "wordpress_pages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("wordpress_object_id", sa.Integer(), nullable=False),
        sa.Column("post_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("slug", sa.String(length=512), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("wordpress_modified_at", sa.String(length=64), nullable=True),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "wordpress_object_id",
            "post_type",
            name="uq_wordpress_page_identity",
        ),
    )
    op.create_index(
        op.f("ix_wordpress_pages_project_id"),
        "wordpress_pages",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "page_audits",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("wordpress_page_id", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("page_type_label", sa.String(length=32), nullable=False),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["wordpress_page_id"], ["wordpress_pages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_page_audits_project_id"), "page_audits", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_page_audits_wordpress_page_id"),
        "page_audits",
        ["wordpress_page_id"],
        unique=False,
    )
    op.create_table(
        "seo_recommendations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("wordpress_page_id", sa.String(length=64), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.String(length=24), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column(
            "approval_state",
            sa.String(length=24),
            server_default="proposed",
            nullable=False,
        ),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["wordpress_page_id"], ["wordpress_pages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seo_recommendations_project_id"),
        "seo_recommendations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seo_recommendations_wordpress_page_id"),
        "seo_recommendations",
        ["wordpress_page_id"],
        unique=False,
    )
    op.create_table(
        "seo_issues",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("page_audit_id", sa.String(length=64), nullable=False),
        sa.Column("issue_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=24), server_default="open", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["page_audit_id"], ["page_audits.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seo_issues_page_audit_id"),
        "seo_issues",
        ["page_audit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seo_issues_project_id"), "seo_issues", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_seo_issues_project_id"), table_name="seo_issues")
    op.drop_index(op.f("ix_seo_issues_page_audit_id"), table_name="seo_issues")
    op.drop_table("seo_issues")
    op.drop_index(
        op.f("ix_seo_recommendations_wordpress_page_id"),
        table_name="seo_recommendations",
    )
    op.drop_index(
        op.f("ix_seo_recommendations_project_id"), table_name="seo_recommendations"
    )
    op.drop_table("seo_recommendations")
    op.drop_index(op.f("ix_page_audits_wordpress_page_id"), table_name="page_audits")
    op.drop_index(op.f("ix_page_audits_project_id"), table_name="page_audits")
    op.drop_table("page_audits")
    op.drop_index(op.f("ix_wordpress_pages_project_id"), table_name="wordpress_pages")
    op.drop_table("wordpress_pages")
    op.drop_index(
        op.f("ix_wordpress_connections_project_id"), table_name="wordpress_connections"
    )
    op.drop_table("wordpress_connections")
    # ### end Alembic commands ###
