"""add google search console

Revision ID: 0004_google_search_console
Revises: 0003_jobs_subscriptions_usage
Create Date: 2026-06-13 02:18:37.750053
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004_google_search_console"
down_revision: str | None = "0003_jobs_subscriptions_usage"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "google_connections",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("google_subject", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("encrypted_access_token", sa.Text(), nullable=False),
        sa.Column("encrypted_refresh_token", sa.Text(), nullable=True),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "google_subject", name="uq_google_user_subject"),
    )
    op.create_index(
        op.f("ix_google_connections_user_id"),
        "google_connections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "google_oauth_states",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("code_verifier", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash"),
    )
    op.create_index(
        op.f("ix_google_oauth_states_project_id"),
        "google_oauth_states",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_google_oauth_states_user_id"),
        "google_oauth_states",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "gsc_connections",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("google_connection_id", sa.String(length=64), nullable=False),
        sa.Column("property_uri", sa.String(length=2048), nullable=False),
        sa.Column("permission_level", sa.String(length=64), nullable=True),
        sa.Column(
            "state", sa.String(length=24), server_default="connected", nullable=False
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["google_connection_id"], ["google_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index(
        op.f("ix_gsc_connections_google_connection_id"),
        "gsc_connections",
        ["google_connection_id"],
        unique=False,
    )
    op.create_table(
        "gsc_page_performance",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("property_uri", sa.String(length=2048), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("page_url", sa.String(length=2048), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("ctr", sa.Float(), nullable=False),
        sa.Column("average_position", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "property_uri", "date", "page_url", name="uq_gsc_page_day"
        ),
    )
    op.create_index(
        op.f("ix_gsc_page_performance_project_id"),
        "gsc_page_performance",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "gsc_queries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("property_uri", sa.String(length=2048), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("query", sa.String(length=2048), nullable=False),
        sa.Column("page_url", sa.String(length=2048), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("ctr", sa.Float(), nullable=False),
        sa.Column("average_position", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "property_uri",
            "date",
            "query",
            "page_url",
            name="uq_gsc_query_page_day",
        ),
    )
    op.create_index(
        op.f("ix_gsc_queries_project_id"), "gsc_queries", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gsc_queries_project_id"), table_name="gsc_queries")
    op.drop_table("gsc_queries")
    op.drop_index(
        op.f("ix_gsc_page_performance_project_id"), table_name="gsc_page_performance"
    )
    op.drop_table("gsc_page_performance")
    op.drop_index(
        op.f("ix_gsc_connections_google_connection_id"), table_name="gsc_connections"
    )
    op.drop_table("gsc_connections")
    op.drop_index(
        op.f("ix_google_oauth_states_user_id"), table_name="google_oauth_states"
    )
    op.drop_index(
        op.f("ix_google_oauth_states_project_id"), table_name="google_oauth_states"
    )
    op.drop_table("google_oauth_states")
    op.drop_index(
        op.f("ix_google_connections_user_id"), table_name="google_connections"
    )
    op.drop_table("google_connections")
    # ### end Alembic commands ###
