"""add ga4

Revision ID: 0005_ga4
Revises: 0004_google_search_console
Create Date: 2026-06-13 10:13:20.116937
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0005_ga4"
down_revision: str | None = "0004_google_search_console"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ga4_connections",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("google_connection_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=True),
        sa.Column("property_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "state", sa.String(length=24), server_default="connected", nullable=False
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["google_connection_id"], ["google_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_index(
        op.f("ix_ga4_connections_google_connection_id"),
        "ga4_connections",
        ["google_connection_id"],
        unique=False,
    )
    op.create_table(
        "ga4_page_performance",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("property_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("page_path", sa.String(length=2048), nullable=False),
        sa.Column("sessions", sa.Integer(), nullable=False),
        sa.Column("active_users", sa.Integer(), nullable=False),
        sa.Column("engagement_rate", sa.Float(), nullable=False),
        sa.Column("key_events", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "property_id", "date", "page_path", name="uq_ga4_page_day"
        ),
    )
    op.create_index(
        op.f("ix_ga4_page_performance_project_id"),
        "ga4_page_performance",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "ga4_traffic_sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("property_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=512), nullable=False),
        sa.Column("medium", sa.String(length=512), nullable=False),
        sa.Column("campaign", sa.String(length=512), nullable=False),
        sa.Column("sessions", sa.Integer(), nullable=False),
        sa.Column("active_users", sa.Integer(), nullable=False),
        sa.Column("engagement_rate", sa.Float(), nullable=False),
        sa.Column("key_events", sa.Integer(), nullable=False),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "property_id",
            "date",
            "source",
            "medium",
            "campaign",
            name="uq_ga4_source_day",
        ),
    )
    op.create_index(
        op.f("ix_ga4_traffic_sources_project_id"),
        "ga4_traffic_sources",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ga4_traffic_sources_project_id"), table_name="ga4_traffic_sources"
    )
    op.drop_table("ga4_traffic_sources")
    op.drop_index(
        op.f("ix_ga4_page_performance_project_id"), table_name="ga4_page_performance"
    )
    op.drop_table("ga4_page_performance")
    op.drop_index(
        op.f("ix_ga4_connections_google_connection_id"), table_name="ga4_connections"
    )
    op.drop_table("ga4_connections")
    # ### end Alembic commands ###
