"""add crawl analysis

Revision ID: 0006_crawls
Revises: 0005_ga4
Create Date: 2026-06-13 10:21:30.506842
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006_crawls"
down_revision: str | None = "0005_ga4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_webhook_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("webhook_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("webhook_id"),
    )
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_crawl_id", sa.String(length=128), nullable=True),
        sa.Column("root_url", sa.String(length=2048), nullable=False),
        sa.Column("url_limit", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("page_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_crawl_id"),
    )
    op.create_index(
        op.f("ix_crawl_runs_project_id"), "crawl_runs", ["project_id"], unique=False
    )
    op.create_table(
        "crawl_pages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("crawl_run_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("normalized_url", sa.String(length=2048), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.String(length=2048), nullable=True),
        sa.Column("robots", sa.String(length=255), nullable=True),
        sa.Column("markdown", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("indexable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"], ["crawl_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crawl_run_id", "url", name="uq_crawl_page_url"),
    )
    op.create_index(
        op.f("ix_crawl_pages_crawl_run_id"),
        "crawl_pages",
        ["crawl_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_pages_project_id"), "crawl_pages", ["project_id"], unique=False
    )
    op.create_table(
        "crawl_issues",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("crawl_run_id", sa.String(length=64), nullable=False),
        sa.Column("crawl_page_id", sa.String(length=64), nullable=True),
        sa.Column("issue_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crawl_page_id"], ["crawl_pages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"], ["crawl_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crawl_issues_crawl_page_id"),
        "crawl_issues",
        ["crawl_page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_issues_crawl_run_id"),
        "crawl_issues",
        ["crawl_run_id"],
        unique=False,
    )
    op.create_table(
        "crawl_links",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("crawl_page_id", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column("anchor", sa.Text(), nullable=True),
        sa.Column("internal", sa.Boolean(), nullable=False),
        sa.Column("follow", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crawl_page_id"], ["crawl_pages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crawl_page_id", "target_url", name="uq_crawl_page_target"),
    )
    op.create_index(
        op.f("ix_crawl_links_crawl_page_id"),
        "crawl_links",
        ["crawl_page_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crawl_links_crawl_page_id"), table_name="crawl_links")
    op.drop_table("crawl_links")
    op.drop_index(op.f("ix_crawl_issues_crawl_run_id"), table_name="crawl_issues")
    op.drop_index(op.f("ix_crawl_issues_crawl_page_id"), table_name="crawl_issues")
    op.drop_table("crawl_issues")
    op.drop_index(op.f("ix_crawl_pages_project_id"), table_name="crawl_pages")
    op.drop_index(op.f("ix_crawl_pages_crawl_run_id"), table_name="crawl_pages")
    op.drop_table("crawl_pages")
    op.drop_index(op.f("ix_crawl_runs_project_id"), table_name="crawl_runs")
    op.drop_table("crawl_runs")
    op.drop_table("crawl_webhook_events")
    # ### end Alembic commands ###
