"""add recommendation metadata

Revision ID: 0007_recommendations
Revises: 0006_crawls
Create Date: 2026-06-13 10:35:31.747155
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0007_recommendations"
down_revision: str | None = "0006_crawls"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seo_recommendations",
        sa.Column("provider", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "seo_recommendations", sa.Column("model", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "seo_recommendations",
        sa.Column("evidence_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "seo_recommendations",
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "seo_recommendations",
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
    )
    op.create_unique_constraint(
        "seo_recommendations_evidence_hash_key",
        "seo_recommendations",
        ["evidence_hash"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "seo_recommendations_evidence_hash_key",
        "seo_recommendations",
        type_="unique",
    )
    op.drop_column("seo_recommendations", "output_tokens")
    op.drop_column("seo_recommendations", "input_tokens")
    op.drop_column("seo_recommendations", "evidence_hash")
    op.drop_column("seo_recommendations", "model")
    op.drop_column("seo_recommendations", "provider")
    # ### end Alembic commands ###
