"""add wordpress change history

Revision ID: 0008_wordpress_changes
Revises: 0007_recommendations
Create Date: 2026-06-13 10:42:49.309633
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0008_wordpress_changes"
down_revision: str | None = "0007_recommendations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wordpress_change_proposals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("wordpress_page_id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_id", sa.String(length=64), nullable=True),
        sa.Column("change_type", sa.String(length=64), nullable=False),
        sa.Column("before_value", sa.JSON(), nullable=False),
        sa.Column("after_value", sa.JSON(), nullable=False),
        sa.Column("base_content_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "approval_state",
            sa.String(length=24),
            server_default="proposed",
            nullable=False,
        ),
        sa.Column("proposed_by", sa.String(length=64), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_content_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["recommendation_id"], ["seo_recommendations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["wordpress_page_id"], ["wordpress_pages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wordpress_change_proposals_project_id"),
        "wordpress_change_proposals",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wordpress_change_proposals_wordpress_page_id"),
        "wordpress_change_proposals",
        ["wordpress_page_id"],
        unique=False,
    )
    op.create_table(
        "wordpress_change_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("mutation_type", sa.String(length=24), nullable=False),
        sa.Column("before_value", sa.JSON(), nullable=False),
        sa.Column("after_value", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("provider_response", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["wordpress_change_proposals.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wordpress_change_events_project_id"),
        "wordpress_change_events",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wordpress_change_events_proposal_id"),
        "wordpress_change_events",
        ["proposal_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wordpress_change_events_proposal_id"),
        table_name="wordpress_change_events",
    )
    op.drop_index(
        op.f("ix_wordpress_change_events_project_id"),
        table_name="wordpress_change_events",
    )
    op.drop_table("wordpress_change_events")
    op.drop_index(
        op.f("ix_wordpress_change_proposals_wordpress_page_id"),
        table_name="wordpress_change_proposals",
    )
    op.drop_index(
        op.f("ix_wordpress_change_proposals_project_id"),
        table_name="wordpress_change_proposals",
    )
    op.drop_table("wordpress_change_proposals")
    # ### end Alembic commands ###
