"""add user preferences and branding

Revision ID: 0009_preferences
Revises: 0008_wordpress_changes
Create Date: 2026-06-13 10:47:31.720489
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0009_preferences"
down_revision: str | None = "0008_wordpress_changes"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "brand_name",
            sa.String(length=160),
            server_default="WP FixPilot",
            nullable=False,
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "primary_color",
            sa.String(length=7),
            server_default="#173b2d",
            nullable=False,
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "accent_color",
            sa.String(length=7),
            server_default="#d7ff54",
            nullable=False,
        ),
    )
    op.add_column(
        "profiles",
        sa.Column("locale", sa.String(length=8), server_default="nl", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "locale")
    op.drop_column("organizations", "accent_color")
    op.drop_column("organizations", "primary_color")
    op.drop_column("organizations", "brand_name")
    # ### end Alembic commands ###
